language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - ./vendor/bin/.phpunit

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=9
    - COMPOSER_FLAGS="--no-interaction --no-suggest"
    - PHPUNIT_FLAGS="-v"

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: SYMFONY_VERSION=4.* dependencies=lowest
    - php: 7.2
      env: SYMFONY_VERSION=4.* COVERAGE=true PHPUNIT_FLAGS="-v --coverage-clover=coverage.xml --coverage-text" RUN_PHPSTAN=true
    - php: 7.2
      env: SYMFONY_VERSION=5.*
    - php: 7.3
      env: SYMFONY_VERSION=4.*
    - php: 7.3
      env: SYMFONY_VERSION=5.*
    - php: 7.4
      env: SYMFONY_VERSION=4.*
    - php: 7.4
      env: SYMFONY_VERSION=5.*  RUN_PHPSTAN=true
    - php: nightly
      env: SYMFONY_VERSION=5.* dependencies=unstable
  allow_failures:
    - php: nightly

before_install:
  - if [ "$dependencies" == "unstable" ]; then composer config minimum-stability dev; fi
  - composer config extra.symfony.require $SYMFONY_VERSION

install:
  - composer install ${COMPOSER_FLAGS}
  - if [ "$dependencies" == "lowest" ]; then composer update --prefer-lowest --prefer-stable ${COMPOSER_FLAGS}; fi

before_script:
  - composer validate --strict --no-check-lock

script:
  - ./vendor/bin/phpunit ${PHPUNIT_FLAGS}
  - if [ "$RUN_PHPSTAN" == "true" ]; then composer phpstan; fi

after_success:
  - if [[ $COVERAGE = true ]]; then bash <(curl -s https://codecov.io/bash); fi
